apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
  labels:
    app: alertmanager
    release: prometheus
data:
  alertmanager.yaml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'alanzit0xz@gmail.com'
      smtp_auth_username: 'alanzit0xz@gmail.com'
      smtp_auth_password: 'odbq gykm lqzd qvwf'
      smtp_require_tls: true

    route:
      receiver: 'gmail-notifications'
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1h

    receivers:
    - name: 'gmail-notifications'
      email_configs:
      - to: 'alanzit0xz@gmail.com'
        send_resolved: true
