apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    name: grafana-datasources
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service.default.svc.cluster.local
        isDefault: true
